#LISTA DEPARTAMENTOS
SELECT SIGLA, NOME FROM DEPARTAMENTO
ORDER BY(NOME);

#######################################################
#LISTA DEPENDENTES 
SELECT COLABORADOR.NOME,
		DEPENDENTE.NOME,
		DEPENDENTE.DATA_NASCIMENTO,
        DEPENDENTE.PARENTESCO
FROM DEPENDENTE INNER JOIN COLABORADOR
ON DEPENDENTE.COLABORADOR = COLABORADOR.MATRICULA ORDER BY COLABORADOR.NOME, DEPENDENTE.NOME;

#######################################################
#INSERCAO NOVO COLAB EM PROJETO
INSERT INTO COLABORADOR 
VALUES
('AAAA', '376.577.270-00', 'Fulano de Tal', 'Fulano@email.com', 'Fulano@corp.com', '15000.00', 'DIR', '71222-100', 'Casa 1');

INSERT INTO PROJETO 
(nome, responsavel, inicio, fim)
VALUES
('BI', 'AAAA', '2022-08-01', NULL);

INSERT INTO TELEFONE_COLABORADOR
VALUES
('(61)9 9999-9999', 'AAAA', 'M');

INSERT INTO PAPEL 
(nome)
VALUES
('Especialista de Negócios');

INSERT INTO ATRIBUICAO
(colaborador, projeto, papel)
VALUES
('AAAA', 5, 8);

#######################################################
#EXCLUSAO DEPTO SECAP:
SELECT * FROM COLABORADOR WHERE DEPARTAMENTO = 'SECAP';
DELETE FROM ATRIBUICAO WHERE COLABORADOR IN ('H123', 'M123', 'R123', 'W123');
DELETE FROM TELEFONE_COLABORADOR WHERE COLABORADOR IN ('H123', 'M123', 'R123', 'W123');
DELETE FROM DEPENDENTE WHERE COLABORADOR IN ('H123', 'M123', 'R123', 'W123');
UPDATE DEPARTAMENTO SET CHEFE = 'AAAA'WHERE sigla = 'SECAP';
DELETE FROM COLABORADOR WHERE DEPARTAMENTO = 'SECAP';
DELETE FROM DEPARTAMENTO WHERE SIGLA = 'SECAP';